title: Application settings

summary: >-
  Allows to edit repository URL, username, author name and email.

contents: |

  == Repository URL

  This is the address of the Git repository that is used to version
  Glossarist data. All collaborators of single concept system should specify the same URL.

  IMPORTANT: Repository URL must be in the following format:
  `\https://<domain name>/<user>/<repository>`. There must be no trailing slash.

  == Username

  Git username of you, Glossarist Desktop user. It is used for authentication with Git.

  == Name

  Your name, to be associated with your edits.

  == Email

  Your email will be used to identify your revisions as yours.

  == See also

  - link:../../../adopt/2-infrastructure[How to set up Glossarist repository using GitHub]
